#!/usr/bin/env Rscript

library(ggplot2)

#TZX248-Chr11
#datasub
data=read.csv("/SelfMapping_AB_correction/TZX248_AB_correction.csv",header=T)
colnames(data)=c("chr","start","end","value")
data$pos=(data[,2]+data[,3])/2
data[["sign"]]=ifelse(data[["value"]]>=0,"positive","negative")
datasub=data[which(data[,1]=="Chr11"),]
#plot
pdf("compartment-TZX248-Chr11.pdf",width=30,height=10)
ggplot(data=datasub,mapping=aes(x=pos,y=value,fill=sign))+
geom_bar(stat="identity",position="dodge",width=100000)+
theme_classic()+
theme(axis.text.x=element_text(size=15),axis.text.y=element_text(size=15),axis.title.x=element_text(size=15),axis.title.y=element_text(size=15),legend.position="none")+
scale_fill_manual(values=c("#d9534f","#428bca"))+
scale_x_continuous(limits=c(0,65000000),breaks=seq(0,60000000,10000000),labels=seq(0,60,10))+
scale_y_continuous(limits=c(-2,2),breaks=seq(-2,2,2),labels=seq(-2,2,2))+
labs(x="",y="")+
geom_segment(x=0,y=0,xend=max(datasub[,3]),yend=0,size=1)
dev.off()

#TZX248-Chr13
#datasub
data=read.csv("/SelfMapping_AB_correction/TZX248_AB_correction.csv",header=T)
colnames(data)=c("chr","start","end","value")
data$pos=(data[,2]+data[,3])/2
data[["sign"]]=ifelse(data[["value"]]>=0,"positive","negative")
datasub=data[which(data[,1]=="Chr13"),]
#plot
pdf("compartment-TZX248-Chr13.pdf",width=30,height=10)
ggplot(data=datasub,mapping=aes(x=pos,y=value,fill=sign))+
geom_bar(stat="identity",position="dodge",width=100000)+
theme_classic()+
theme(axis.text.x=element_text(size=15),axis.text.y=element_text(size=15),axis.title.x=element_text(size=15),axis.title.y=element_text(size=15),legend.position="none")+
scale_fill_manual(values=c("#d9534f","#428bca"))+
scale_x_continuous(limits=c(0,65000000),breaks=seq(0,60000000,10000000),labels=seq(0,60,10))+
scale_y_continuous(limits=c(-2,2),breaks=seq(-2,2,2),labels=seq(-2,2,2))+
labs(x="",y="")+
geom_segment(x=0,y=0,xend=max(datasub[,3]),yend=0,size=1)
dev.off()

#TZX544-Chr11
#datasub
data=read.csv("/SelfMapping_AB_correction/TZX544_AB_correction.csv",header=T)
colnames(data)=c("chr","start","end","value")
data$pos=(data[,2]+data[,3])/2
data[["sign"]]=ifelse(data[["value"]]>=0,"positive","negative")
datasub=data[which(data[,1]=="Chr11"),]
#plot
pdf("compartment-TZX544-Chr11.pdf",width=30,height=10)
ggplot(data=datasub,mapping=aes(x=pos,y=value,fill=sign))+
geom_bar(stat="identity",position="dodge",width=100000)+
theme_classic()+
theme(axis.text.x=element_text(size=15),axis.text.y=element_text(size=15),axis.title.x=element_text(size=15),axis.title.y=element_text(size=15),legend.position="none")+
scale_fill_manual(values=c("#d9534f","#428bca"))+
scale_x_continuous(limits=c(0,65000000),breaks=seq(0,60000000,10000000),labels=seq(0,60,10))+
scale_y_continuous(limits=c(-2,2),breaks=seq(-2,2,2),labels=seq(-2,2,2))+
labs(x="",y="")+
geom_segment(x=0,y=0,xend=max(datasub[,3]),yend=0,size=1)
dev.off()

#TZX544-Chr13
#datasub
data=read.csv("/SelfMapping_AB_correction/TZX544_AB_correction.csv",header=T)
colnames(data)=c("chr","start","end","value")
data$pos=(data[,2]+data[,3])/2
data[["sign"]]=ifelse(data[["value"]]>=0,"positive","negative")
datasub=data[which(data[,1]=="Chr13"),]
#plot
pdf("compartment-TZX544-Chr13.pdf",width=30,height=10)
ggplot(data=datasub,mapping=aes(x=pos,y=value,fill=sign))+
geom_bar(stat="identity",position="dodge",width=100000)+
theme_classic()+
theme(axis.text.x=element_text(size=15),axis.text.y=element_text(size=15),axis.title.x=element_text(size=15),axis.title.y=element_text(size=15),legend.position="none")+
scale_fill_manual(values=c("#d9534f","#428bca"))+
scale_x_continuous(limits=c(0,65000000),breaks=seq(0,60000000,10000000),labels=seq(0,60,10))+
scale_y_continuous(limits=c(-2,2),breaks=seq(-2,2,2),labels=seq(-2,2,2))+
labs(x="",y="")+
geom_segment(x=0,y=0,xend=max(datasub[,3]),yend=0,size=1)
dev.off()
